version: 2

models:
  - name: twitter_campaign_data
    description: "Twitter data extracted from a data pipeline"
    columns: 
      - name: campaign_id
        tests:
          - not_null
      - name: influencer_id
        tests:
          - not_null
      - name: task_id
        tests:
          - not_null
      - name: tweet_id
        tests:
          - not_null
      - name: tweet_text
      - name: username
      - name: submission_link
      - name: channel
      - name: created_at
      - name: error
      - name: followers_count
      - name: hashtags
      - name: likes
      - name: location
      - name: possibly_sensitive
      - name: profile_location
      - name: quote_count
      - name: reply_count
      - name: retweet_count
      - name: source
      - name: stage
      - name: status
      - name: processed_at
sources:
    - name: twitter_api
      #For bigquery:
      database: bi-staging-1-309112
      schema: dbt_caleb
      tables:
        - name: campaign_expenditure
        - name: twitter_campaign_data_redux