SELECT 
  i.id,
  i.doc_number,
  i.linked_txn_txnId,
  i.linked_txntype,
  i.line_id,
  i.line_description,
  i.line_detailtype,
  i.line_classrefname,
  i.line_classrefvalue,
  i.line_itemRefname,
  i.line_line_amount,
  i.create_time,
  i.line_servicedate,
  i.txn_date,
  i.due_date,
  i.last_updatedtime,
  i.total_amt,
  i.currency_name,
  JSON_EXTRACT(i.CustomerMemo, '$.value') CustomerMemo,
  i.ExchangeRate,
  p.line_amount payment_line_amt,
  p.linkedtxn_txid payment_linkedtxn_txid,
  p.linkedtxn_txntype payment_linkedtxn_txntype,
  p.TxnDate payment_TxnDate,
  p.create_time payment_create_time,
  p.TotalAmt payment_TotalAmt,
  p.currency_name payment_currency_name,
  p.currency payment_currency,
  p.customer_name payment_customer_name,
  p.PrivateNote payment_PrivateNote,
  p.ExchangeRate payment_ExchangeRate,
  p.ProcessPayment payment_ProcessPayment
FROM {{ ref('quickbooks_stg__invoices') }} i  
LEFT JOIN {{ ref('quickbooks_stg__payments') }} p ON i.linked_txn_txnId = p.id 