SELECT 
  id,
  Line,
  JSON_EXTRACT_SCALAR(Line, '$[0].Amount') AS line_amount,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(Line, '$[0].LinkedTxn'), '$[0].TxnId') AS linkedtxn_txid,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(Line, '$[0].LinkedTxn'), '$[0].TxnType') AS linkedtxn_txntype,
  domain,
  sparse,
  TxnDate,
  MetaData,
  JSON_EXTRACT(MetaData, '$.CreateTime') AS create_time,
  JSON_EXTRACT(MetaData, '$.LastUpdatedTime') AS lastupdate_time,
  TotalAmt,
  LinkedTxn,
  SyncToken,
  CurrencyRef,
  JSON_EXTRACT(CurrencyRef, '$.name') AS currency_name,
  JSON_EXTRACT(CurrencyRef, '$.value') AS currency,
  CustomerRef,
  JSON_EXTRACT(CustomerRef, '$.name') AS customer_name,
  PrivateNote,
  ARAccountRef,
  ExchangeRate,
  UnappliedAmt,
  PaymentRefNum,
  ProcessPayment,
  PaymentMethodRef,
  DepositToAccountRef
FROM {{ source('staging', 'payments') }}