SELECT 
  --CurrencyRef,
  JSON_EXTRACT_SCALAR(CurrencyRef, '$.name') AS currency_name,
  JSON_EXTRACT_SCALAR(CurrencyRef, '$.value') AS currency,
  ExchangeRate,
  TxnDate,
  --DepartmentRef,
  JSON_EXTRACT_SCALAR(DepartmentRef, '$.name') AS DepartmentRefName,
  JSON_EXTRACT_SCALAR(DepartmentRef, '$.value') AS DepartmentRefValue,
  --Line,
  JSON_VALUE(item, '$.LineNum') AS LineNum,
  JSON_VALUE(item, '$.Description') AS Line_Description,
  JSON_VALUE(item, '$.AccountBasedExpenseLineDetail.ClassRef.name') AS Line_ClassRef_Name,
  JSON_VALUE(item, '$.AccountBasedExpenseLineDetail.ClassRef.value') AS Line_ClassRef_Value,
  JSON_VALUE(item, '$.AccountBasedExpenseLineDetail.TaxCodeRef.value') AS Line_TaxCodeRef_Value,
  JSON_VALUE(item, '$.AccountBasedExpenseLineDetail.BillableStatus') AS Line_BillableStatus,
  JSON_VALUE(item, '$.AccountBasedExpenseLineDetail.AccountRef.name') AS Line_AccountRef_Name,
  JSON_VALUE(item, '$.AccountBasedExpenseLineDetail.AccountRef.value') AS Line_AccountRef_Value,
  JSON_VALUE(item, '$.DetailType') AS Line_DetailType,
  JSON_VALUE(item, '$.Amount') AS Line_Amount,
  JSON_VALUE(item, '$.Id') AS Line_Id,
  SyncToken,
  sparse,
  TotalAmt,
  --MetaData,
  JSON_EXTRACT_SCALAR(MetaData, '$.CreateTime') AS CreateTime,
  JSON_EXTRACT_SCALAR(MetaData, '$.LastUpdatedTime') AS LastUpdatedTime,
  domain,
  DocNumber,
  --APAccountRef,
  JSON_EXTRACT_SCALAR(APAccountRef, '$.name') AS APAccountRefName,
  JSON_EXTRACT_SCALAR(APAccountRef, '$.value') AS APAccountRefValue,
  --SalesTermRef,
  JSON_EXTRACT_SCALAR(SalesTermRef, '$.value') AS SalesTermRefValue,
  id,
  DueDate,
  --VendorRef,
  JSON_EXTRACT_SCALAR(VendorRef, '$.name') AS VendorRefName,
  JSON_EXTRACT_SCALAR(VendorRef, '$.value') AS VendorRefValue,
  Balance,
  PrivateNote,
  LinkedTxn
FROM {{ source('staging', 'bills') }}, 
UNNEST(Line) AS item