SELECT 
  id,
  Line as Line_data,
  JSON_EXTRACT_SCALAR(Line, '$[0].Amount') AS Line_Amount,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(Line, '$[0].LinkedTxn[0]'), '$.TxnId') AS TxnId,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(Line, '$[0].LinkedTxn[0]'), '$.TxnType') AS Txn_Type,
  domain,
  sparse,
  PayType,
  TxnDate,
  MetaData,
  JSON_EXTRACT_SCALAR(MetaData, '$.CreateTime') AS CreateTime,
  JSON_EXTRACT_SCALAR(MetaData, '$.LastUpdatedTime') AS LastUpdatedTime,
  TotalAmt,
  DocNumber,
  SyncToken,
  VendorRef,
  JSON_EXTRACT_SCALAR(VendorRef, '$.name') AS vendor_name,
  CurrencyRef,
  JSON_EXTRACT_SCALAR(CurrencyRef, '$.name') AS currency_name,
  APAccountRef,
  CheckPayment,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(CheckPayment, '$.BankAccountRef'), '$.name') AS BankAccountName,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(CheckPayment, '$.BankAccountRef'), '$.value') AS BankAccountValue,
  JSON_EXTRACT_SCALAR(CheckPayment, '$.PrintStatus') AS PrintStatus,
  ExchangeRate,
  DepartmentRef,
  CreditCardPayment
FROM {{ source('staging', 'bill_payments') }}  