select
    id as influencer_id,
    code,
    role,
    email,
    avatar,
    gender,
    country,
    date(dob_date) as dob_date,
    location,
    platform,
    last_name,
    timestamp(created_at) as created_at,
    first_name,
    push_token,
    timestamp(updated_at) as updated_at,
    code_attempts,
    date(timestamp(creation_time)) as date_account_created,
    mobile_number,
    code_timestamp,
    email_verified,
    payment_method,
    income_category,
    income_currency,
    personal_id_number,
    smileidentity_status,
    accepted_terms_version,
    mobile_number_verified,
    notification_new_job_offer,
    notification_post_rejected,
    notification_post_problematic,
    notification_campaign_canceled,
    notification_campaign_starts_soon,
    notification_influencer_group_add,
    notification_smileidentity_result,
    notification_influencer_group_invitation,
    notification_campaign_ends_soon_no_sm_posts_yet,
    notification_social_media_account_needs_relinking
from {{ source('staging', 'influencers') }}
