SELECT
    id,
    transfer_id,
    influencer_id,
    task_id,
    account_number,
    bank_code,
    fullname,
    provider,
    date(creation_time) as date_created,
    currency,
    exchange_rate,
    tax_amount,
    amount,
    fee,
    status,
    reference,
    narration,
    approver,
    complete_message,
    requires_approval,
    is_approved,
    bank_name,
    payment_method,
    creation_time,
    date(processed_date) as processed_date,
    payment_eligible_at,
    updated_at

FROM {{ source('staging', 'influencer_transfers') }}