
version: 2

models:
  - name: stg_influencer_first_campaign
    description: "First campaign date by influencer"
    columns:
      - name: influencer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_influencer_last_campaign
    description: "Last campaign date by influencer"
    columns:
      - name: influencer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_total_jobs_per_influencer
    description: "Total jobs by influencer: offered, accepted, expired, not accepted"
    columns:
      - name: influencer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_approval_rates
    description: "Approval rates in each step verification: 1st, 2nd and 3rd."
    columns:
      - name: influencer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: stg_influencer_demographics
    description: "Influencer basic information"
    columns:
      - name: influencer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_distinct_groups_per_influencer
    description: "Count of groups by influencer"
    columns:
      - name: influencer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: distinct_groups
        description: "Total of groups the influencer has"

  - name: stg_jobs_last_months
    description: "Count of jobs ACCEPTED by the influencer in: last 6 months, last 3 months, last 2 months, last month, last 4 weeks, last 2 weeks, last week"
    columns:
      - name: influencer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: jobs_last_3_months
        description: "Total of jobs the influencer accepted in the last 3 months"
      - name: jobs_last_month
        description: "Total of jobs the influencer accepted in the last month"
      - name: jobs_last_6_months
        description: "Total of jobs the influencer accepted in the last 6 months"
      - name: jobs_last_2_months
        description: "Total of jobs the influencer accepted in the last 2 months"
      - name: jobs_last_2_weeks
        description: "Total of jobs the influencer accepted in the last 2 weeks"
      - name: jobs_last_4_weeks
        description: "Total of jobs the influencer accepted in the last 4 weeks"
      - name: jobs_last_week
        description: "Total of jobs the influencer accepted last week"

  - name: stg_first_campaign_complete_and_paid
    description: "First Task Completed and Paid by influencer"
    columns:
      - name: influencer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_merchant_payments
    description: "Staging merchant payment model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: created
        description: "Date payment created"
      - name: merchant_id
        description: "Merchant ID"
        tests:
          - not_null
      - name: campaign_id
        description: "Campaign ID"
        tests:
          - not_null
      - name: amount
        description: ""
      - name: currency
        description: ""
      - name: ref_x
        description: ""
      - name: transfer_status
        description: ""
      - name: flw_ref
        description: ""
      - name: campaign_name
        description: ""

  - name: stg_bank_details
    description: "Updated Bank Details"
    columns:
      - name: influencer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

sources:
    - name: staging
      #For bigquery:
      database: bi-staging-1-309112
      schema: wowzi_data
      tables:
        - name: influencer_tasks
        - name: influencers
        - name: influencer_group_influencers
        - name: influencer_groups
        - name: jobs
        - name: influencer_transfers
        - name: merchant_payments
