select
    id,
    id as campaign_id,
    name,
    cast(company_id as INT64) as company_id,
    cast(merchant_id as INT64) as merchant_id,
    start_date,
    end_date,
    description,
    budget,
    currency,
    gender,
    canceled,
    canceled_timestamp,
    canceled_by_merchant_id,
    canceled_by_backofficer_id,
    date(timestamp(creation_time)) as campaign_creation_date,
    init_called,
    payment_plan,
    pre_live_check_status,
    pre_live_check_backofficer_id,
    pre_live_check_comment,
    pre_live_check_internal_comment,
    pre_live_check_timestamp,
    monday_from,		
    monday_to,
    tuesday_from,
    tuesday_to,
    wednesday_from,
    wednesday_to,
    thursday_from,
    thursday_to,
    friday_from,
    friday_to,
    saturday_from,
    saturday_to,
    sunday_from,
    sunday_to,
    multi_campaign,
    bonus_amount,
    bonus_type
FROM {{ source('core', 'campaigns') }}