with source as (

    select * from {{ source('hubspot_staging', 'deals') }}

),

renamed as (

    select
        id,
        archived,
        contacts,
        companies,
        createdat,
        updatedat,
        line_items,
        JSON_EXTRACT_SCALAR(properties, "$.payment_net") AS properties_payment_net,
        properties_amount,
        properties_hs_acv,
        properties_hs_arr,
        properties_hs_mrr,
        properties_hs_tcv,
        properties_dealname as dealname,
        properties_dealtype as dealtype,
        properties_pipeline as pipeline,
        properties_closedate as closedate,
        properties_dealstage as dealstage,
        properties_num_notes as num_notes,
        properties_po_number as po_number,
        properties_po_upload,
        properties_createdate,
        properties_hs_tag_ids,
        properties_description,
        properties_hs_priority as hs_priority,
        properties_hs_is_closed as hs_is_closed,
        properties_hs_next_step,
        properties_hs_object_id,
        properties_days_to_close as days_to_close,
        properties_hs_createdate,
        properties_hs_deal_score,
        properties_deal___country as deal___country,
        properties_deal___segment,
        properties_deal___won_time,
        properties_hs_all_team_ids as hs_all_team_ids,
        properties_hs_was_imported,
        properties_hubspot_team_id as hubspot_team_id,
        properties_proposal_upload,
        properties_deal_loss_reason as deal_loss_reason,
        properties_hs_all_owner_ids as hs_all_owner_ids,
        properties_hs_closed_amount as hs_closed_amount,
        properties_hs_exchange_rate,
        properties_hs_is_closed_won as hs_is_closed_won,
        properties_hs_is_open_count as hs_is_open_count,
        properties_hs_object_source,
        properties_hubspot_owner_id as hubspot_owner_id,
        properties_closed_won_reason,
        properties_closed_lost_reason as closed_lost_reason,
        properties_deal_currency_code as deal_currency_code,
        properties_hs_closed_won_date as hs_closed_won_date,
        properties_hs_forecast_amount as hs_forecast_amount,
        properties_hs_shared_team_ids,
        properties_hs_shared_user_ids,
        properties_notes_last_updated,
        properties_hs_analytics_source,
        properties_hs_closed_won_count as hs_closed_won_count,
        properties_hs_lastmodifieddate,
        properties_hs_object_source_id,
        properties_hs_predicted_amount,
        properties_hs_projected_amount,
        properties_num_contacted_notes,
        properties_hs_days_to_close_raw,
        properties_hs_merged_object_ids,
        properties_hs_time_in_closedwon as hs_time_in_closedwon,
        properties_notes_last_contacted as notes_last_contacted,
        properties_annual_contract_value,
        properties_hs_created_by_user_id as hs_created_by_user_id,
        properties_hs_time_in_closedlost,
        properties_hs_updated_by_user_id as hs_updated_by_user_id,
        properties_hs_likelihood_to_close,
        properties_hs_num_target_accounts,
        properties_hs_object_source_label,
        properties_hs_unique_creation_key,
        properties_amount_in_home_currency,
        properties_hs_forecast_probability,
        properties_hs_pinned_engagement_id,
        properties_hs_time_in_contractsent,
        properties_num_associated_contacts,
        properties_deal___select_brand_name as deal___select_brand_name,
        properties_hs_date_exited_closedwon,
        properties_hs_object_source_user_id,
        properties_hs_open_deal_create_date,
        properties_notes_next_activity_date as notes_next_activity_date,
        properties_hs_closed_deal_close_date,
        properties_hs_date_entered_closedwon,
        properties_hs_date_exited_closedlost,
        properties_hs_deal_stage_probability as deal_stage_probability,
        properties_hs_date_entered_closedlost as hs_date_entered_closedlost,
        properties_hs_latest_meeting_activity,
        properties_hubspot_owner_assigneddate as hubspot_owner_assigneddate,
       from source

)

select * from renamed
