WITH referred_jobs AS 
(
SELECT  
  influencer_id,
  company_id,
  industry,
  campaign_id,
  campaign_end_date,
  job_id,
  job_offer_date,
  task_id,
  task_creation_date,
  tasks_assigned,
  job_status,
  completed_tasks,
  amount_lcy,
  campaign_currency,
  amount_usd,
  payment_date,
  platfrom_job_value_lcy,
  currency_rate,
  payment_amount_list_usd,
  inf_first_name,
  inf_last_name,
  created,
  first_campaign_date,
  inf_last_campaign_date,
  days_to_job,
  days_since_last_campaign,
  gender,
  dob,
  inf_age,
  age_groups,
  country,
  invitation_status,
  Instagram_influencer_level,
  Facebook_influencer_level,
  X_influencer_level,
  Linkedin_influencer_level,
  Tiktok_influencer_level,
  channel,
  influencer_level,
  datasource,
  first_job_date,
  id_card_type,
  no_of_tasks,
  refugee_flag,
  mon_yr,
  active_l3m,
  active_l3m_completed_tasks,
  amount_paid_to_active_l3m,
  creation_to_job_days,
  job_in_reg_month,
  company_name,
  role,
  company_role,
  mon_yr_rnk,
  payment_monyr_rnk,
  distinct_inf,
  all_time_qualified_inf
FROM `bi-staging-1-309112.wowzi_dbt_prod.influencer_job_breakdown` 
  WHERE lower(job_status) IN ('complete', 'ongoing', 'failed')
  AND influencer_id IN 
  (SELECT 
  DISTINCT influencer_id
FROM `bi-staging-1-309112.wowzi_dbt_prod.postgres_stg__influencer_referral_influencer`)
),

ambassadors AS 
(
SELECT 
  r.influencer_id,
  r.referred_by_influencer_id,
  rc.code
FROM {{ ref('postgres_stg__influencer_referral_influencer') }} r
LEFT JOIN {{ ref('influencer_referral_code') }} rc 
    ON r.referred_by_influencer_id = rc.influencer_id
)

SELECT 
    rj.influencer_id,
    a.referred_by_influencer_id,
    a.code referral_code,
    company_id,
    industry,
    campaign_id,
    campaign_end_date,
    job_id,
    job_offer_date,
    task_id,
    task_creation_date,
    tasks_assigned,
    job_status,
    completed_tasks,
    amount_lcy,
    campaign_currency,
    amount_usd,
    payment_date,
    platfrom_job_value_lcy,
    currency_rate,
    payment_amount_list_usd,
    inf_first_name,
    inf_last_name,
    created,
    first_campaign_date,
    inf_last_campaign_date,
    days_to_job,
    days_since_last_campaign,
    gender,
    dob,
    inf_age,
    age_groups,
    country,
    invitation_status,
    Instagram_influencer_level,
    Facebook_influencer_level,
    X_influencer_level,
    Linkedin_influencer_level,
    Tiktok_influencer_level,
    channel,
    influencer_level,
    datasource,
    first_job_date,
    id_card_type,
    no_of_tasks,
    refugee_flag,
    mon_yr,
    active_l3m,
    active_l3m_completed_tasks,
    amount_paid_to_active_l3m,
    creation_to_job_days,
    job_in_reg_month,
    company_name,
    role,
    company_role,
    mon_yr_rnk,
    payment_monyr_rnk,
    distinct_inf,
    all_time_qualified_inf
FROM referred_jobs rj 
LEFT JOIN ambassadors a ON rj.influencer_id = a.influencer_id