SELECT 
  parse_date('%d/%m/%Y', date)  invoice_date,
  Transaction_type transaction_type,
  safe_cast(Number as int64)  invoice_no,
  Name billing_client_name,
  Description invoice_desc,
  Account_2 account_name,
  SAFE_CAST(REPLACE(Amount, ',', '') AS INT64) invoice_amt,
  safe_cast(Exch_Rate as int64) exch_rate,
  SAFE_CAST(REPLACE(USD_Value, ',', '') AS INT64) invoice_amt_usd,
  EOMonth invoice_month,
  SAFE_CAST(REPLACE(Influencer_Payable_Amount, ',', '') AS INT64) creator_payable_amt,
  SAFE_CAST(REPLACE(Gross_Profit, ',', '') AS INT64) gross_profit,
  SAFE_CAST(REPLACE(Gross_Profit, ',', '') AS INT64) / safe_cast(Exch_Rate as int64) gross_profit_usd,
  GP_Margin gp_margin,
  Campaigns_Calc campaigns_calc,
  Client client,
  Brand brand,
  Market_Segment market_segment,
  Region region,
  Country country,
  Agency_Direct agency_direct,
  Agency_Name agency_name,
  SAFE_CAST(REPLACE(Actual_Influencer_Payable, ',', '') AS INT64) actual_influencer_payable,
  Type event_type,
  Net_Payment_Days 
FROM  {{ source('staging', 'gsheets_sales_accruals') }} 
  WHERE Transaction_type IS NOT NULL